#Project
In this project, we use publicly available e-commerce transaction data and supervised machine learning techniques to build a model that predicts which customers are most likely to become repeat purchasers. This will help WitOmni identify high-value customer segments, prioritize marketing efforts, and develop more effective customer retention strategies.

In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import tensorflow.keras as keras
from sklearn.preprocessing import StandardScaler
import time

In [ ]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.13/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
online_retail = fetch_ucirepo(id=352)

# data (as pandas dataframes)
X = online_retail.data.features
y = online_retail.data.targets

# metadata
print(online_retail.metadata)

# variable information
print(online_retail.variables)

{'uci_id': 352, 'name': 'Online Retail', 'repository_url': 'https://archive.ics.uci.edu/dataset/352/online+retail', 'data_url': 'https://archive.ics.uci.edu/static/public/352/data.csv', 'abstract': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.', 'area': 'Business', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate', 'Sequential', 'Time-Series'], 'num_instances': 541909, 'num_features': 6, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': None, 'index_col': ['InvoiceNo', 'StockCode'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Oct 21 2024', 'dataset_doi': '10.24432/C5BW33', 'creators': ['Daqing Chen'], 'intro_paper': {'ID': 361, 'type': 'NATIVE', 'title': 'Data mining for the online retail industry: A case study of RFM model-based customer segmentation using data mining', 'authors': 'Daqing Chen, Sai Laing Sain, Kun Guo', 'venue': 'Journal of Database Marketing and Customer Strategy Management, Vol. 19, No. 3', 'year': 2012, 'journal': None, 'DOI': '10.1057/dbm.2012.17', 'URL': 'https://www.semanticscholar.org/paper/e43a5a90fa33d419df42e485099f8f08badf2149', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.The company mainly sells unique all-occasion gifts. Many customers of the company are wholesalers.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation. \nStockCode: Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.\nDescription: Product (item) name. Nominal.\nQuantity: The quantities of each product (item) per transaction. Numeric.\t\nInvoiceDate: Invoice Date and time. Numeric, the day and time when each transaction was generated.\nUnitPrice: Unit price. Numeric, Product price per unit in sterling.\nCustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.\nCountry: Country name. Nominal, the name of the country where each customer resides. ", 'citation': None}}
          name     role         type demographic  \
0    InvoiceNo       ID  Categorical        None
1    StockCode       ID  Categorical        None
2  Description  Feature  Categorical        None
3     Quantity  Feature      Integer        None
4  InvoiceDate  Feature         Date        None
5    UnitPrice  Feature   Continuous        None
6   CustomerID  Feature  Categorical        None
7      Country  Feature  Categorical        None

                                         description     units missing_values
0  a 6-digit integral number uniquely assigned to...      None             no
1  a 5-digit integral number uniquely assigned to...      None             no
2                                       product name      None             no
3  the quantities of each product (item) per tran...      None             no
4  the day and time when each transaction was gen...      None             no
5                             product price per unit  sterling             no
6  a 5-digit integral number uniquely assigned to...      None             no
7  the name of the country where each customer re...      None             no

Since the dataset does not come with a predefined target variable (`y`), we need to construct it based on the problem statement. Our goal is to predict 'repeat purchasers'. First, let's create a complete DataFrame by combining the features (`X`) with the ID columns (`InvoiceNo`, `StockCode`) which were separated.

In [ ]:
invoice_stock_ids = online_retail.data.ids
df = pd.concat([invoice_stock_ids, X], axis=1)

display(df.head())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

Now that we have the full dataframe, we can define the target variable `y`. A 'repeat purchaser' can be defined as a customer who has made more than one purchase. We can identify these customers by counting the number of unique `InvoiceNo` per `CustomerID`.

In [ ]:
# Calculate the number of unique invoices per customer
num_invoices_per_customer = df.groupby('CustomerID')['InvoiceNo'].nunique()

# Define repeat purchasers (those with more than 1 invoice)
repeat_purchasers = num_invoices_per_customer[num_invoices_per_customer > 1].index

# Create the target variable 'y': 1 if a repeat purchaser, 0 otherwise
df['is_repeat_purchaser'] = df['CustomerID'].isin(repeat_purchasers).astype(int)

# Display the first few rows with the new target variable and its distribution
display(df[['CustomerID', 'is_repeat_purchaser']].drop_duplicates().head())
print(df['is_repeat_purchaser'].value_counts())
print(f"Percentage of repeat purchasers: {df['is_repeat_purchaser'].mean() * 100:.2f}%")

    CustomerID  is_repeat_purchaser
0      17850.0                    1
9      13047.0                    1
26     12583.0                    1
46     13748.0                    1
65     15100.0                    1

is_repeat_purchaser
1    378014
0    163895
Name: count, dtype: int64
Percentage of repeat purchasers: 69.76%

In [ ]:
# Now, we can assign the newly created target variable to 'y'
y = df['is_repeat_purchaser']

# Let's check the shape of y now
print(y.shape)

(541909,)

In [ ]:
print (X.shape)

(541909, 6)

In [ ]:
print(y.shape)

(541909,)

Calculating a new variable for creating a new feature, "average order value"

In [ ]:
#How much is being spent
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]

In [ ]:
# Determining how much a customer is spending in total + number of orders
customer_avg_order = df.groupby("CustomerID").agg(
    total_spent = ("TotalPrice", "sum"),
    num_orders=("InvoiceNo", "nunique")
)

In [ ]:
# Calculating the average order value feature
customer_avg_order["AverageOrderValue"] = (
    customer_avg_order["total_spent"]/ customer_avg_order["num_orders"]
)

Merging the new feature with the original dataset.

In [ ]:
df = df.merge(
    customer_avg_order[["AverageOrderValue"]],
    on="CustomerID",
    how="left"
)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,is_repeat_purchaser,TotalPrice,AverageOrderValue_x,AverageOrderValue_y
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,1,15.30,151.103714,151.103714
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,1,20.34,151.103714,151.103714
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,1,22.00,151.103714,151.103714
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,1,20.34,151.103714,151.103714
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,1,20.34,151.103714,151.103714

In [ ]:
list(df.columns)

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country',
 'is_repeat_purchaser',
 'TotalPrice',
 'AverageOrderValue']

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,...,Country,is_repeat_purchaser,TotalPrice,AverageOrderValue_x,AverageOrderValue_y
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,...,United Kingdom,1,15.30,151.103714,151.103714
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,...,United Kingdom,1,20.34,151.103714,151.103714
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,...,United Kingdom,1,22.00,151.103714,151.103714
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,...,United Kingdom,1,20.34,151.103714,151.103714
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,...,United Kingdom,1,20.34,151.103714,151.103714